export const CHECKOUT_LABELS = {
  common: {
    total: 'Total',
    tableFallback: 'Mesa',
    registerPayment: 'Registrar pago',
    cancelOrder: 'Cancelar pedido',
  },
  dashboard: {
    activeOrdersTitle: 'Pedidos activos',
    noActiveOrders: 'Sin pedidos activos.',
    newOrder: 'Nuevo pedido',
    printComanda: 'Imprimir comanda',
    generatePrecheck: 'Generar precuenta',
    selectTableHint: 'Selecciona una mesa para ver el pedido',
    singleBill: (capacity: number) => `Cuenta única · ${capacity} pers.`,
  },
  billing: {
    ordersTitle: 'Pedidos',
    noOrders: 'Sin pedidos registrados para esta mesa.',
    consolidatedBill: 'Cuenta consolidada',
    noItems: 'Sin ítems en cuenta.',
    capacity: (capacity: number) => `${capacity} pers.`,
    pendingWarning: 'Hay pedidos sin entregar. Confirma antes de cobrar.',
    proceedToPayment: (total: string) => `Proceder al cobro · ${total}`,
    pendingChip: (count: number) => `${count} pendiente${count > 1 ? 's' : ''}`,
    inProgressChip: (count: number) => `${count} en proceso`,
    readyChip: (count: number) => `${count} listo${count > 1 ? 's' : ''}`,
    deliveredChip: (count: number) => `${count} entregado${count > 1 ? 's' : ''}`,
  },
  payment: {
    orderSummary: 'Resumen del pedido',
    totalDue: 'Total a cobrar',
    methodTitle: 'Método de pago',
    amountReceived: 'Monto recibido',
    change: 'Cambio',
    cardInstructions: 'Pase la tarjeta en el terminal y confirme cuando el cobro sea exitoso.',
    processing: 'Procesando…',
    confirm: (total: string) => `Confirmar pago · ${total}`,
  },
  layout: {
    live: 'En vivo',
    logoutShort: 'Salir',
    admin: 'Admin',
    manualAria: 'Abrir manual',
  },
  cancelDialog: {
    note: 'Un administrador debe autorizar esta cancelación con sus credenciales. El pedido cancelado se excluye de la cuenta.',
    reasonLabel: 'Motivo',
    reasonPlaceholder: 'Describe el motivo de la cancelación',
    adminEmailLabel: 'Email del admin',
    adminCredentialLabel: 'PIN o contraseña del admin',
    cancelling: 'Cancelando…',
  },
} as const;
